export default {
  SET_COMPLETED_TODOS: " SET_COMPLETED_TODOS",
  GET_TODOS: "GET_TODOS",
  DELETE_TODO: "DELETE_TODO",
  TODO_LOADING: "TODO_LOADING",
  TODO_ERROR: "TODO_ERROR",
  SET_MESSAGE: "SET_MESSAGE",
};
