export default {
  SET_GENERAL_TODOS: " SET_GENERAL_TODOS",
  ADD_GENERAL_TODO: "ADD_GENERAL_TODO",
  GET_GENERAL_TODOS: "GET_GENERAL_TODOS",
  DELETE_GENERAL_TODO: "DELETE_GENERAL_TODO",
  EDIT_GENERAL_TODO: "EDIT_GENERAL_TODO",
  TODO_GENERAL_LOADING: "TODO_GENERAL_LOADING",
  TODO_POST_GENERAL_LOADING: "TODO_POST_GENERAL_LOADING",
  TODO_GENERAL_ERROR: "TODO_GENERAL_ERROR",
  SET_GENERAL_MESSAGE: "SET_MESSAGE",
  SET_COMPLETED_TODOS_COUNT: "SET_COMPLETED_TODOS_COUNT",
  SET_INCOMPLETE_TODOS_COUNT: "SET_INCOMPLETE_TODOS_COUNT",
};
