export default {
  ADD_TODO: "ADD_TODO",
  GET_TODO_SUCCESS: "GET_TODO_SUCCESS",
  DELETE_TODO: "DELETE_TODO",
  EDIT_TODO: "EDIT_TODO",
  COMPLETE_TODO: "COMPLETE_TODO",
  TODO_LOADING: "TODO_LOADING",
  TODO_ERROR: "TODO_ERROR",
  SET_MESSAGE: "SET_MESSAGE",
};
