export default {
  ADD_TODO: "ADD_TODO",
  ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
  GET_TODOS: "GET_TODOS",
  GET_TODOS_SUCCESS: "GET_TODOS_SUCCESS",
  DELETE_TODO: "DELETE_TODO",
  EDIT_TODO: "EDIT_TODO",
  COMPLETE_TODO: "COMPLETE_TODO",
  TODO_LOADING: "TODO_LOADING",
  TODO_ERROR: "TODO_ERROR",
  SET_MESSAGE: "SET_MESSAGE",
  SET_INCOMPLETE: "SET_INCOMPLETE",
  SET_COMPLETE: "SET_COMPLETE",
};
