export default {
  SIGNUP_USER: "SIGNUP_USER",
  SIGNUP_LOADING: "SIGNUP_LOADING",
  SIGNUP_ERROR: "SIGNUP_ERROR",
  LOGIN_USER: "LOGIN_USER",
  LOGIN_LOADING: "LOGIN_LOADING",
  LOGIN_ERROR: "LOGIN_ERROR",
};
